### ISSUE TITLE
Create your Internship Repo

### ISSUE THREAD

**Issue by kipkurui** [mbbu/Bioinformatics_Internship_Cohort2#1]
[Create your GitHub repo](https://docs.github.com/en/github/getting-started-with-github/create-a-repo). Your repo should outline your vision and provide a Roadmap for your research or work. Here are some resources on how to draft a detailed [README](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) and create a [Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/). 

When you have created your repo, please comment with the link here. Be sure to make the repo public.

**Comment by simeonhebrew** [comment]
**Here is the link to my repo** 

https://github.com/simeonhebrew/Bioinformatics-Internship

**Comment by Asatsa** [comment]
A link to my repo
https://github.com/Asatsa/internship_repo1

**Comment by Gatheru-rose** [comment]
Here is the link to my repo
https://github.com/Gatheru-rose/intern_roadmap

**Comment by Kauthar-Omar** [comment]
Here is the link to my repo
https://github.com/Kauthar-Omar/My-Bioinformatics-Internship

**Comment by wmudaki** [comment]
There goes my link https://github.com/totodingi/bioinformaticsInternship
